name: Node CI

on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: macos-11

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node-14 environment
              uses: actions/setup-node@v2.5.1
              with:
                  node-version: '14'
                  cache: 'yarn'

            - name: Yarn Install, Build, (Test)
              run: |
                  yarn
                  yarn build
            # - name: YARN TEST
            #   run: |
            #       yarn test
